create table public.kami_profiles (
  id uuid not null default extensions.uuid_generate_v4 (),
  kamigotchi_id uuid not null,
  operator_wallet_id uuid not null,
  auto_harvest_enabled boolean null default false,
  harvest_node_index integer null,
  auto_collect_enabled boolean null default false,
  auto_restart_enabled boolean null default false,
  min_health_threshold integer null default 20,
  auto_heal_enabled boolean null default false,
  harvest_schedule_type text null default 'continuous'::text,
  harvest_start_time time without time zone null,
  harvest_end_time time without time zone null,
  harvest_duration integer null default 60,
  rest_duration integer null default 30,
  last_harvest_start timestamp with time zone null,
  last_collect timestamp with time zone null,
  is_currently_harvesting boolean null default false,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint kami_profiles_pkey primary key (id),
  constraint kami_profiles_kamigotchi_id_key unique (kamigotchi_id),
  constraint kami_profiles_kamigotchi_id_fkey foreign KEY (kamigotchi_id) references kamigotchis (id) on delete CASCADE,
  constraint kami_profiles_operator_wallet_id_fkey foreign KEY (operator_wallet_id) references operator_wallets (id) on delete CASCADE
) TABLESPACE pg_default;