export const NODE_LIST = [
  { id: 1, name: "Misty Riverside", affinity: "Eerie" },
  { id: 2, name: "Tunnel of Trees", affinity: "Normal" },
  { id: 3, name: "Torii Gate", affinity: "Normal" },
  { id: 5, name: "Restricted Area", affinity: "Normal" },
  { id: 6, name: "Labs Entrance", affinity: "Eerie" },
  { id: 9, name: "Forest: Old Growth", affinity: "Insect" },
  { id: 10, name: "Forest: Insect Node", affinity: "Insect" },
  { id: 12, name: "Scrap Confluence", affinity: "Scrap" },
  { id: 15, name: "Temple Cave", affinity: "Scrap" },
  { id: 16, name: "Techno Temple", affinity: "Eerie, Scrap" },
  { id: 18, name: "Cave Crossroads", affinity: "Insect" },
  { id: 19, name: "Temple of the Wheel", affinity: "Eerie, Scrap" },
  { id: 25, name: "Lost Skeleton", affinity: "Eerie" },
  { id: 26, name: "Trash-Strewn Graves", affinity: "Eerie" },
  { id: 29, name: "Misty Forest Path", affinity: "Insect" },
  { id: 30, name: "Scrapyard Entrance", affinity: "Scrap" },
  { id: 31, name: "Scrapyard Exit", affinity: "Scrap" },
  { id: 32, name: "Road To Labs", affinity: "Normal" },
  { id: 33, name: "Forest Entrance", affinity: "Normal" },
  { id: 34, name: "Deeper Into Scrap", affinity: "Scrap" },
  { id: 35, name: "Elder Path", affinity: "Normal" },
  { id: 36, name: "Parting Path", affinity: "Insect" },
  { id: 37, name: "Hollow Path", affinity: "Normal" },
  { id: 47, name: "Scrap Paths", affinity: "Scrap" },
  { id: 48, name: "Murky Forest Path", affinity: "Insect" },
  { id: 49, name: "Clearing", affinity: "Normal" },
  { id: 50, name: "Ancient Forest Entrance", affinity: "Insect" },
  { id: 51, name: "Scrap-Littered Undergrowth", affinity: "Insect" },
  { id: 52, name: "Airplane Crash", affinity: "Eerie" },
  { id: 53, name: "Blooming Tree", affinity: "Eerie" },
  { id: 55, name: "Shady Path", affinity: "Normal" },
  { id: 56, name: "Butterfly Forest", affinity: "Insect" },
  { id: 57, name: "River Crossing", affinity: "Normal" },
  { id: 58, name: "Mouth of Scrap", affinity: "Scrap" },
  { id: 59, name: "Black Pool", affinity: "Eerie" },
  { id: 60, name: "Scrap Trees", affinity: "Scrap" },
  { id: 61, name: "Musty Forest Path", affinity: "Normal" },
  { id: 62, name: "Centipedes", affinity: "Insect" },
  { id: 63, name: "Deeper Forest Path", affinity: "Normal" },
  { id: 65, name: "Forest Hut", affinity: "Eerie" },
  { id: 67, name: "Boulder Tunnel", affinity: "Normal" },
  { id: 68, name: "Slippery Pit", affinity: "Normal" },
  { id: 69, name: "Lotus Pool", affinity: "Eerie" },
  { id: 70, name: "Still Stream", affinity: "Normal" },
  { id: 71, name: "Shabby Deck", affinity: "Insect" },
  { id: 72, name: "Hatch to Nowhere", affinity: "Insect, Scrap" },
  { id: 73, name: "Broken Tube", affinity: "Scrap" },
  { id: 74, name: "Engraved Door", affinity: "Eerie" },
  { id: 75, name: "Flood Mural", affinity: "Eerie" },
  { id: 76, name: "Fungus Garden", affinity: "Insect" },
  { id: 77, name: "Thriving Mushrooms", affinity: "Insect" },
  { id: 78, name: "Toadstool Platforms", affinity: "Insect" },
  { id: 79, name: "Abandoned Campsite", affinity: "Normal" },
  { id: 80, name: "Radiant Crystal", affinity: "Eerie" },
  { id: 81, name: "Flower Mural", affinity: "Normal" },
  { id: 82, name: "Geometric Cliffs", affinity: "Scrap" },
  { id: 83, name: "Canyon Bridge", affinity: "Normal" },
  { id: 84, name: "Reinforced Tunnel", affinity: "Scrap" },
  { id: 85, name: "Giant's Palm", affinity: "Normal" },
  { id: 86, name: "Guardian Skull", affinity: "Eerie, Insect" },
  { id: 87, name: "Sacrarium", affinity: "Eerie" },
  { id: 88, name: "Treasure Hoard", affinity: "Scrap" },
  { id: 89, name: "Trophies of the Hunt", affinity: "Insect" },
  { id: 90, name: "Scenic View", affinity: "Eerie" }
];